---
- name: test playbook copy
  hosts: all
  become: true
  tasks:
    - name: copying index.html to node
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0600
