---
- name: This playbook installs a package
  hosts: webservers
  become: true
  tasks:
  - name: Installing httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: starting httpd service

  - name: Installing apache2 
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: starting apache2 service

  - name: copying index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html/
      mode: 0666
        
  handlers:
  - name: starting httpd service
    service:
      name: httpd
      state: started

  - name: starting apache2 service
    service:
      name: apache2
      state: started

